//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.0.1
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public HTuple hv_ExpDefaultWinHandle;

  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_GrayImage, ho_Regions1;
    HObject ho_RegionFillUp, ho_Region2, ho_SelectedRegions;

    // Local control variables 

    HTuple hv_W = new HTuple(), hv_H = new HTuple();
    HTuple hv_WindowHandle = new HTuple(), hv_Number = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_GrayImage);
    HOperatorSet.GenEmptyObj(out ho_Regions1);
    HOperatorSet.GenEmptyObj(out ho_RegionFillUp);
    HOperatorSet.GenEmptyObj(out ho_Region2);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    //大枣计算程序
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "D:/A PIC/DZ1.jpg");
    hv_W.Dispose();hv_H.Dispose();
    HOperatorSet.GetImageSize(ho_Image, out hv_W, out hv_H);
    //dev_close_window(...);
    //dev_open_window(...);
    ho_GrayImage.Dispose();
    HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
    ho_Regions1.Dispose();
    HOperatorSet.Threshold(ho_GrayImage, out ho_Regions1, 4, 150);
    ho_RegionFillUp.Dispose();
    HOperatorSet.FillUp(ho_Regions1, out ho_RegionFillUp);
    ho_Region2.Dispose();
    HOperatorSet.Connection(ho_RegionFillUp, out ho_Region2);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_Region2, out ho_SelectedRegions, "area", "and", 150, 
        99999);
    hv_Number.Dispose();
    HOperatorSet.CountObj(ho_SelectedRegions, out hv_Number);
    HOperatorSet.SetTposition(hv_ExpDefaultWinHandle, 20, 10);
    HOperatorSet.WriteString(hv_ExpDefaultWinHandle, "大枣数量=");
    HOperatorSet.SetTposition(hv_ExpDefaultWinHandle, 20, 70);
    HOperatorSet.WriteString(hv_ExpDefaultWinHandle, hv_Number);

    ho_Image.Dispose();
    ho_GrayImage.Dispose();
    ho_Regions1.Dispose();
    ho_RegionFillUp.Dispose();
    ho_Region2.Dispose();
    ho_SelectedRegions.Dispose();

    hv_W.Dispose();
    hv_H.Dispose();
    hv_WindowHandle.Dispose();
    hv_Number.Dispose();

  }

  public void InitHalcon()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
  }

  public void RunHalcon(HTuple Window)
  {
    hv_ExpDefaultWinHandle = Window;
    action();
  }

}

